// Mock sample patients for quick testing
export const samplePatients = [
  {
    id: 'sample_1',
    name: 'High Risk - Elderly with Comorbidities',
    data: {
      age: 75,
      gender: 'Male',
      heart_rate: 125,
      systolic_bp: 85,
      diastolic_bp: 55,
      respiratory_rate: 28,
      spo2: 88,
      temperature: 101.5,
      gcs_score: 12,
      wbc_count: 18.5,
      hemoglobin: 9.2,
      platelet_count: 120,
      creatinine: 2.8,
      sodium: 132,
      potassium: 5.8,
      glucose: 280,
      lactate: 5.2,
      chest_pain: 1,
      dyspnea: 1,
      altered_consciousness: 1,
      seizure: 0,
      abdominal_pain: 0,
      trauma: 0,
      diabetes: 1,
      hypertension: 1,
      cad: 1,
      copd: 1,
      ckd: 1,
      stroke_history: 0,
      triage_category: 1
    }
  },
  {
    id: 'sample_2',
    name: 'Moderate Risk - Respiratory Distress',
    data: {
      age: 58,
      gender: 'Female',
      heart_rate: 105,
      systolic_bp: 110,
      diastolic_bp: 70,
      respiratory_rate: 32,
      spo2: 89,
      temperature: 100.2,
      gcs_score: 14,
      wbc_count: 14.2,
      hemoglobin: 11.5,
      platelet_count: 185,
      creatinine: 1.3,
      sodium: 138,
      potassium: 4.2,
      glucose: 165,
      lactate: 3.1,
      chest_pain: 0,
      dyspnea: 1,
      altered_consciousness: 0,
      seizure: 0,
      abdominal_pain: 0,
      trauma: 0,
      diabetes: 1,
      hypertension: 1,
      cad: 0,
      copd: 1,
      ckd: 0,
      stroke_history: 0,
      triage_category: 2
    }
  },
  {
    id: 'sample_3',
    name: 'Low Risk - Minor Complaint',
    data: {
      age: 35,
      gender: 'Male',
      heart_rate: 78,
      systolic_bp: 120,
      diastolic_bp: 80,
      respiratory_rate: 16,
      spo2: 98,
      temperature: 98.6,
      gcs_score: 15,
      wbc_count: 8.5,
      hemoglobin: 14.2,
      platelet_count: 250,
      creatinine: 1.0,
      sodium: 140,
      potassium: 4.0,
      glucose: 95,
      lactate: 1.2,
      chest_pain: 0,
      dyspnea: 0,
      altered_consciousness: 0,
      seizure: 0,
      abdominal_pain: 1,
      trauma: 0,
      diabetes: 0,
      hypertension: 0,
      cad: 0,
      copd: 0,
      ckd: 0,
      stroke_history: 0,
      triage_category: 4
    }
  }
];

export const defaultPatientData = {
  age: 55,
  gender: 'Male',
  heart_rate: 85,
  systolic_bp: 130,
  diastolic_bp: 80,
  respiratory_rate: 18,
  spo2: 95,
  temperature: 98.6,
  gcs_score: 15,
  wbc_count: 9.0,
  hemoglobin: 13.0,
  platelet_count: 250,
  creatinine: 1.0,
  sodium: 140,
  potassium: 4.0,
  glucose: 100,
  lactate: 1.5,
  chest_pain: 0,
  dyspnea: 0,
  altered_consciousness: 0,
  seizure: 0,
  abdominal_pain: 0,
  trauma: 0,
  diabetes: 0,
  hypertension: 0,
  cad: 0,
  copd: 0,
  ckd: 0,
  stroke_history: 0,
  triage_category: 3
};
